version: "3"
services:
    app:
        image: kiwilightweight/php-fpm53
#        ports:
#            - "127.0.0.1:9081:9000"
        volumes:
            - ./data/drupal6:/var/www/html
        environment:
            - SMTP_HOST=mail.davelane.nz
            - SMTP_PORT=587
            - SMTP_REPLYTO_EMAIL=no-reply@davelane.nz
            - SMTP_AUTH_USER=smtp@davelane.nz
            - SMTP_AUTH_PASSWORD=ItbA29rmDQ9fzLuGx
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - d6.local
    cron:
        image: kiwilightweight/php-fpm53-cron
        links:
            - app
        volumes:
            - ./data/drupal6:/var/www/html
        environment:
            - SMTP_HOST=mail.davelane.nz
            - SMTP_PORT=587
            - SMTP_REPLYTO_EMAIL=no-reply@davelane.nz
            - SMTP_AUTH_USER=smtp@davelane.nz
            - SMTP_AUTH_PASSWORD=ItbA29rmDQ9fzLuGx
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - cron.d6.local
    nginx:
        image: oeru/nginx-jessie
        links:
            - app
        ports:
            - "127.0.0.1:8085:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/includes:/etc/nginx/includes
            - ./nginx/cache:/var/cache/nginx
            - ./data/drupal6:/var/www/html
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - nginx.d6.local
